language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'
  - DB=pgsql db_dsn='postgres://travis@127.0.0.1/cakephp_test'

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1

install:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

before_script:
  - sh -c "if [ '$PHPCS' = '1' ]; then composer require squizlabs/php_codesniffer; fi"

  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev satooshi/php-coveralls:dev-master; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then mkdir -p build/logs; fi"

  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"
  - phpenv rehash
  - set +H
  - cp phpunit.xml.dist phpunit.xml

script:
  - sh -c "if [ '$PHPCS' != '1' ]; then phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then ./vendor/bin/phpcs -p --extensions=php --standard=psr2 --ignore=tests/bootstrap.php ./src ; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then phpunit --stderr --coverage-clover build/logs/clover.xml; fi"

after_script:
  - sh -c "if [ '$COVERALLS' = '1' ]; then php vendor/bin/coveralls -c .coveralls.yml -v; fi"

notifications:
  email: false
